---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/MavenAnsibleWebApp-CICD/target/MavenAnsibleWebApp.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp.war"
        remote_src: no
    
    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes

    - name: Wait for Tomcat to stop
      pause:
        seconds: 5

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
